### ISSUE TITLE
左侧项目目录树边栏不能自己再拉宽一点么？

### ISSUE THREAD

**Issue by 61mon** [jawil/GayHub#12]
（做的很不错）

**Comment by jawil** [comment]
后续会完善，支持自己任意宽度拉伸

**Comment by 61mon** [comment]
期待...

**Comment by huage2580** [comment]
1.5.3还是不支持自己拉宽。

**Comment by jawil** [comment]
把这个忘了😂，这个优先级比较低，插件通信设置那块还在开发。。。

**Comment by huage2580** [comment]
readme里面写个todo和update吧，方便查(催)看(更)

**Comment by jawil** [comment]
还有人建议我把其他几个插件集成一下，最近开发量有点大，不想用别人的代码，全是jQuery，所以自己用E6开发有点慢

**Comment by 1900han** [comment]
@jawil 期待
