### ISSUE TITLE
插件整合

### ISSUE THREAD

**Issue by ReZeroS** [jawil/GayHub#15]
大佬你的插件好像可以替了 github octree 和 github avatar 这俩

那 对于 

- github plus（显示项目文件大小）

- github hovercard(这个很赞, 悬浮显示info卡)

- aweosme complete for github(类似tab补全后提供相关搜索)

有啥操作么?

另外感觉大V的gay头像logo,,,,,有点骚气啊。。。

**Comment by ReZeroS** [comment]
补一句，，主题开启在哪？没找到。。。。

**Comment by jawil** [comment]
你说的这些，我到时候也整合进去，时间有限，先把难度最大的TOC和侧边栏整出来了，其他再慢慢加😂

**Comment by ReZeroS** [comment]
牛逼啊大佬，大佬加油

**Comment by jawil** [comment]
其实早就想做一个全部整合的插件，只是一直没动手做，看见那些jquery写的插件，我内心毫无波澜，决定用ES6重新写 😂

**Comment by jawil** [comment]
主题bug有点多，样式乱了一些，暂时下线了
