### ISSUE TITLE
进去到某一个详细页面的时候,会莫名的卡死

### ISSUE THREAD

**Issue by crper** [jawil/GayHub#17]
环境:
1. MACOS 10.12
2. Chrome 61

比如进入到项目二级目录的时候..直接访问的时候...会一直转圈圈,有时候等了很久就出来了;
有些情况直接卡到页面崩溃

出现了几次了...

**Comment by jawil** [comment]
这个昨天已经修复了，请更新到最新版@crper

**Comment by crper** [comment]
@jawil  大佬,,我是商店安装的...一般都会自动更新吧

**Comment by jawil** [comment]
你看下你现在的版本，最新版本是1.5.1

**Comment by crper** [comment]
@jawil 1.5,删除了重新在线安装依旧1.5 .....

**Comment by jawil** [comment]
现在还会卡死吗？能不能给个你那个卡死的链接给我测试一下，看看我这边有问题没。@crper
昨天这个问题issure有提到，我可能修复的还有点问题。

**Comment by jawil** [comment]
我在掘金群里怎么找不到你了

**Comment by crper** [comment]
暂时没法复现了...把浏览器关闭了再访问那个又好了..

微信群??在的大佬,WeChat:MY1083

**Comment by jawil** [comment]
找了半天爱折腾的crper 啥来着，怎么没看到？
