### ISSUE TITLE
TOC导航 bug

### ISSUE THREAD

**Issue by blankPen** [jawil/GayHub#19]
- 刚进入页面时还没滚动过滚动条TOC导航点击没反应。
- 点击TOC导航时常崩溃，点着点着就没了。
- 好吧，其实我是来骗邀请码的

![bug](https://user-images.githubusercontent.com/20318672/30511170-dc2f3972-9b05-11e7-8f40-8896aa1631f8.gif)

**Comment by jawil** [comment]
点着点着就没了是咋回事，刚进入页面时还没滚动过滚动条TOC导航点击没反应这个好像我也测出来了，正在修复。

**Comment by blankPen** [comment]
就是你一直点导航，有一定几率就消失了，观察了下是transform的计算出了问题。
![image](https://user-images.githubusercontent.com/20318672/30527783-d2477e56-9c5e-11e7-88ba-44c190f57b59.png)

**Comment by jawil** [comment]
是不是你用的其他插件冲突还是啥的，这个模块我好像没使用transform这个属性，搜了一下代码也没看到。
