### ISSUE TITLE
github上添加新文件／或编辑时，会上下生成两个编辑区域

### ISSUE THREAD

**Issue by cji03** [jawil/GayHub#22]
刚添加了一个新文件，发现编辑区怎么换行都没用，编辑不了，向下翻了一下发现还有一个编辑区，这个才是可以用的，不知道是原本的设计还是bug，感觉被虚晃了。
![gayhub](https://user-images.githubusercontent.com/25778928/30550572-d3bd56b4-9c65-11e7-8ed7-ccc495296bc8.png)

**Comment by jawil** [comment]
是个bug，已经修复，明天chrome会自动升级
