### ISSUE TITLE
首页图像展示

### ISSUE THREAD

**Issue by tomgao365** [jawil/GayHub#23]
![image](https://user-images.githubusercontent.com/13798931/30572233-fdaedeca-9d1e-11e7-9cf6-2995e6cf9c93.png)

只有这个哥们的头像显示不出来
https://github.com/bsansouci

这个插件可以显示出来
https://chrome.google.com/webstore/detail/avatars-for-github/pgjmdbklnfklcjfbonjfkdhaonlfogbb?utm_source=chrome-app-launcher-info-dialog
![image](https://user-images.githubusercontent.com/13798931/30572405-f9b5c01c-9d1f-11e7-9680-e42c9dd73c30.png)

**Comment by jawil** [comment]
已经修复，谢谢反馈

**Comment by tomgao365** [comment]
Good
