### ISSUE TITLE
有需要用Typescript重写吗, 乐意PR

### ISSUE THREAD

**Issue by axetroy** [jawil/GayHub#26]
使用JS浑身不自在....

使用Typescript, 代码可读性大大提高, 减少N多BUG...

好吧, 我就是来安利的

**Comment by jawil** [comment]
额，没用过啊，原生JavaScript控。语法bug对于我来说很少了，主要还是业务逻辑的bug，考虑不周全，这个不管用那种语言都是很难避免的，至于代码可读性代码多了逻辑复杂了都不好理解别人的思维😂

**Comment by axetroy** [comment]
typescript写法与js并没有差异，只是类型检测系统。
用起来会很爽

**Comment by jawil** [comment]
有了解过，但是没有具体去做项目用过，就是JavaScript的超集，对ES6/7/8也完美支持

**Comment by jawil** [comment]
后续代码都会慢慢重构优化，哈哈，现在主要开发核心功能，还有好几个模块没时间开发

**Comment by axetroy** [comment]
有一个是.

里面的代码, 经常有扩写原生对象的方法.

这就导致了, 有些地方代码逻辑不清晰, 不推荐这么做...

比如这里

```javascript
const attr = (HTMLElement.prototype.attr = function(attr, value) {
  return arguments[1] == void 0
    ? this.getAttribute(attr)
    : this.setAttribute(attr, value);
});
```

**Comment by jawil** [comment]
主要是模拟JQ的attr方法，偷个懒少些代码，getAttribute有点太长了
