### ISSUE TITLE
在看gist代码的时候有BUG。

### ISSUE THREAD

**Issue by g00dhacker** [jawil/GayHub#29]
在访问某个gist.github.com/xxxx 代码时候。页面顶栏错位。左侧边栏一直滚动但是加载不出

**Comment by jawil** [comment]
没有做gist域名资源请求的适配。。。能给我个具体地址，我抽空兼容一下

**Comment by g00dhacker** [comment]
开启gayhub插件之后，任意一个gist资源都有一样的问题

**Comment by jawil** [comment]
好滴，收到
