### ISSUE TITLE
about theme

### ISSUE THREAD

**Issue by nic611** [jawil/GayHub#3]
How to switch dark theme???

**Comment by jawil** [comment]
只有我能开启，此功能还在修改中，很多东西要改，还是觉得不是很满意，所以当初就下线了。1.4版本估计会正式放上去

**Comment by nic611** [comment]
One more suggestion, according to my experience，side menus’s trasition animation could be a little bit more faster. ^_^

**Comment by nic611** [comment]
![image](https://user-images.githubusercontent.com/8542939/30419612-9e7b2e66-98fc-11e7-866b-fe8ff3dc206f.png)
MacBook Pro 13-inch,  responsive problem, might  affect the interaction.

**Comment by jawil** [comment]
Ok,thank you for the tips, I will solve these experiences are not very good place
