### ISSUE TITLE
copy.png 背景不透明

### ISSUE THREAD

**Issue by junbaor** [jawil/GayHub#32]
文件: `https://github.com/jawil/GayHub/blob/d323cca2c6/chrome/icons/copy.png`

注意观察右边的复制按钮，底部是白色.

![QQ截图20170925135744.png](https://i.loli.net/2017/09/25/59c89c005b3a3.png)

**Comment by jawil** [comment]
恩，我重新找一张图标换一换

**Comment by itgoyo** [comment]
@jawil 项目中的图片已经被替换成透明的，但是在商店里边的插件还是白色底的 ，商店的版本可不可以也更新一下，如果导入插件的话chrome会老是提示是否禁用该插件等麻烦字眼。

**Comment by jawil** [comment]
忘记更新到商店了了。。。我这更新一下
