### ISSUE TITLE
你好，我这加载文件目录树有点问题

### ISSUE THREAD

**Issue by howie6879** [jawil/GayHub#34]
如图：
![11](https://user-images.githubusercontent.com/17047388/31306749-eeb0e7c8-ab1b-11e7-8bc4-8e9722f0f53c.png)

**Comment by jawil** [comment]
知道原因了，正则匹配出了点问题，data把database的文件匹配进去了。。。我会立马修复

**Comment by howie6879** [comment]
恩恩 还有个疑问 比如打开一个项目 会加载目录树并显示出来 我手动关闭目录树收缩到左侧  下次打开一个项目  还是会默认加载目录树并显示出来  这个不能记住我上次的操作是关闭了显示目录树的么？

**Comment by jawil** [comment]
这需求暂时没有，过段时间项目不那么忙时候会集中精力把这些都完善，谢谢反馈

**Comment by jawil** [comment]
已更新，之前忘记更新到chrome商店了:逃)
