### ISSUE TITLE
在git项目的二级目录下打开或者刷新，无法进行目录的生成

### ISSUE THREAD

**Issue by linqiang007** [jawil/GayHub#4]
这是请求:
![image](https://user-images.githubusercontent.com/12245095/30419005-82fa6c04-9967-11e7-83c2-3d0d470d3d27.png)
应该是获取到地址多了目录，无法请求吧。

陷入死循环
PS:也就在二级页面刷新，或者直接复制别人地址打开二级页面时会发生吧。

**Comment by jawil** [comment]
你好，你出错的链接能给我一下吗，我这边看看，我打开过各种层级的目录，是不是还漏掉了啥

**Comment by jawil** [comment]
就是你打开的那个地址，不是API请求的这个接口地址

**Comment by linqiang007** [comment]
@jawil https://github.com/ustbhuangyi/better-scroll/tree/master/config

**Comment by jawil** [comment]
我知道，谢谢，我这边出问题了，确实我只考虑到了文件解析，没考虑到目录的默认解析

**Comment by jawil** [comment]
issue问题均已修复，等1.4版本一起发布
