### ISSUE TITLE
git bomb

### ISSUE THREAD

**Issue by ReZeroS** [jawil/GayHub#40]
发现个好玩的东西

大佬快来看看能不能操作一波

https://github.com/Katee/git-bomb

**Comment by jawil** [comment]
GG,数据拉取了半天

**Comment by ReZeroS** [comment]
我这边插件第一层只能显示1个d0，剩下的d[1-9]解析不出来

不过这个库好像本来就是吃内存玩的, 只是好奇能不能当作给gayhub插件作个性能啥测试之类的
