### ISSUE TITLE
可以加上左侧导航栏的下载功能吗

### ISSUE THREAD

**Issue by zhangyt93** [jawil/GayHub#43]
现在点击下载那个小图标只是收缩列表，不会下载，加上下载功能的话，下载单个文件就方便很多，谢谢。

**Comment by shenzekun** [comment]
close #44

**Comment by jawil** [comment]
下载文件吗，还是下载啥来着

**Comment by zhangyt93** [comment]
恩 下载单个文件，之前用的Octotree也有这个功能
![qq 20171031101817](https://user-images.githubusercontent.com/17688171/32204562-f38479b0-be24-11e7-801f-2305493409f8.png)
点击后只下载单个文件

**Comment by jawil** [comment]
这样啊，了解

**Comment by zhangyt93** [comment]
好的 如果有时间的话就加上吧 谢啦 关闭了
