### ISSUE TITLE
有个小 bug

### ISSUE THREAD

**Issue by shenzekun** [jawil/GayHub#44]
右侧导航栏，当标题数目多的时候，就看不到下面的字了，希望改进下

![](https://ws3.sinaimg.cn/large/006tNc79ly1fl0g4v986lj318i0mgdh3.jpg)

![](https://ws4.sinaimg.cn/large/006tNc79ly1fl0g6qmupnj317q0x8773.jpg)

**Comment by jawil** [comment]
TOC目录看不到吗，是右边看不到还是下面看不到了？

**Comment by shenzekun** [comment]
下面看不到了 @jawil

**Comment by jawil** [comment]
没有滚动条吗？😂

**Comment by shenzekun** [comment]
对😂

**Comment by shenzekun** [comment]
就一直卡在那😁，下不去。。。

**Comment by jawil** [comment]
把你这个链接发给我，我看一下，我这边别的都有滚动条的

**Comment by shenzekun** [comment]
https://github.com/shenzekun/shenzekun.github.io/issues/1 @jawil

**Comment by jawil** [comment]
你这个标题太太多了，有的还不是按照正常的嵌套顺序，不过已经修复了，，，

**Comment by shenzekun** [comment]
👍

**Comment by shenzekun** [comment]
close #44

**Comment by shenzekun** [comment]
fixes #44
