### ISSUE TITLE
右侧导航目录样式不对了。。

### ISSUE THREAD

**Issue by axuebin** [jawil/GayHub#45]
![image](https://user-images.githubusercontent.com/13316392/32274054-1b096cf4-bf40-11e7-8889-a9b4c0b0fc75.png)
![image](https://user-images.githubusercontent.com/13316392/32274059-1fbc87c2-bf40-11e7-8e24-d3a91500480a.png)

浏览器：Chrome 62.0.3202.75

**Comment by jawil** [comment]
之前是好的然后最近变成这样的吗？请问你是什么操作系统的chrome，我这边mac下一切现实正常。。。

**Comment by axuebin** [comment]
之前都是好着的。。 win10的Chrome

**Comment by jawil** [comment]
我回滚了一个版本，你等会看看是不是自动升到1.6.0版本了，然后子再看看样式正常不。

样式问题我这边没法重现。。。先回滚一个版本试一试

**Comment by axuebin** [comment]
… 我明早看看，再给你消息

**Comment by axuebin** [comment]
现在没问题了。。

![image](https://user-images.githubusercontent.com/13316392/32304579-675beff8-bfab-11e7-9c32-3ea82a039426.png)

 现在就是1.6的啊。。

不知道啥毛病 - -
