### ISSUE TITLE
每次打开项目，都会在右侧都会弹出一个table of content 的弹框，很是不友好，建议默认关闭，或者给个开关进行关闭。

### ISSUE THREAD

**Issue by tanranran** [jawil/GayHub#6]
<img width="1612" alt="qq20170914-173033 2x" src="https://user-images.githubusercontent.com/5227840/30422417-7e5a61e8-9905-11e7-8bd6-3f2eda5ebe5b.png">

**Comment by tanranran** [comment]
搜索项目的时候也会出现。。。明明已经隐藏了，下次搜索还会出现。。。。。

**Comment by jawil** [comment]
好滴，陆续都会加入

**Comment by tanranran** [comment]
@jawil 
爱死你了。

**Comment by jawil** [comment]
有什么需求或者好点子，尽管说，实现不鸟算我输 @tanranran 😂

**Comment by tanranran** [comment]
<img width="496" alt="wx20170915-152627 2x" src="https://user-images.githubusercontent.com/5227840/30471201-63f2f1b8-99bd-11e7-8417-504db1a14fc7.png">

左边的目录 宽度太小，不能调节，在项目层级多的情况下，和文件名称长的情况下，看不完整。

**Comment by jawil** [comment]
好滴，有什么问题去issue里面提，我好统一完善。@tanranran

https://github.com/jawil/GayHub/issues
