### ISSUE TITLE
文件无法单独下载

### ISSUE THREAD

**Issue by Meowv** [jawil/GayHub#7]
#### 作者 参考一下这个Chrome插件 Octotree 是可以下载的。

**Comment by jawil** [comment]
请问是什么文件？仓库页面的单个文件吗

**Comment by Meowv** [comment]
左侧列表 鼠标放上去 不是会显示下载的小图标吗。点击无法下载该文件

**Comment by Meowv** [comment]
还有一个Bug哦，二级目录下，点击下载小图标会折叠当前二级目录。
