### ISSUE TITLE
代码复制有bug

### ISSUE THREAD

**Issue by zljs** [jawil/GayHub#9]
代码复制不能用，而且出现了无限多个复制按钮
![360 16831115435067](https://user-images.githubusercontent.com/24908420/30424422-87c00e22-9978-11e7-9186-06dda5973a6a.png)

**Comment by jawil** [comment]
恩恩，会立即修复，发布新的插件版本，刚开始bug可能有点多

**Comment by jawil** [comment]
所有issure的bug均已修复，感谢大家的反馈
